---
apiVersion: v2
type: application
name: observability-grafana
description: A Helm chart for deploying Grafana observability stack for pulse-hub application
version: 0.1.0
appVersion: "latest"
dependencies:
  - name: prometheus
    version: "28.13.0"
    repository: https://prometheus-community.github.io/helm-charts
  - name: grafana
    repository: oci://ghcr.io/grafana-community/helm-charts/grafana
    version: "11.3.7"
