loki:
  deploymentMode: SingleBinary
  singleBinary:
    replicas: 1
    persistence:
      enabled: true
    extraVolumes:
      - name: loki-var
        emptyDir: {}

    extraVolumeMounts:
      - name: loki-var
        mountPath: /var/loki

  read:
    replicas: 0
  write:
    replicas: 0
  backend:
    replicas: 0
  gateway:
    enabled: false
  chunksCache:
    enabled: false
  resultsCache:
    enabled: false
  lokiCanary:
    enabled: false
  test:
    enabled: false
  loki:
    auth_enabled: false
    commonConfig:
      replication_factor: 1
    containerSecurityContext:
      readOnlyRootFilesystem: false
    schemaConfig:
      configs:
        - from: "2024-01-01"
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h
    storage:
      type: filesystem
      bucketNames:
        chunks: chunks
        ruler: ruler
        admin: admin

prometheus:
  alertmanager:
    enabled: false
  kube-state-metrics:
    enabled: false
  prometheus-node-exporter:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  server:
    replicaCount: 1
    persistentVolume:
      enabled: false
    retention: "6h"
scrapeConfigs:
  prometheus:
    enabled: true
  kubernetes-api-servers:
    enabled: false
  kubernetes-nodes:
    enabled: false
  kubernetes-nodes-cadvisor:
    enabled: false
  kubernetes-service-endpoints:
    enabled: false
  kubernetes-service-endpoints-slow:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  kubernetes-services:
    enabled: false
  kubernetes-pods:
    enabled: false
  kubernetes-pods-slow:
    enabled: false
