prometheus:
  alertmanager:
    enabled: false
  kube-state-metrics:
    enabled: false
  prometheus-node-exporter:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  server:
    replicaCount: 1
    persistentVolume:
      enabled: false
    retention: "6h"

  scrapeConfigs:
    opentelemetry-collector:
      enabled: true
      job_name: "opentelemetry-collector"
      honor_labels: true
      static_configs:
        - targets:
            - "pulse-hub-otel-collector:8889"
      metrics_path: "/metrics"
      scrape_interval: 30s
      scrape_timeout: 10s
    prometheus:
      enabled: true
    kubernetes-api-servers:
      enabled: false
    kubernetes-nodes:
      enabled: false
    kubernetes-nodes-cadvisor:
      enabled: false
    kubernetes-service-endpoints:
      enabled: false
    kubernetes-service-endpoints-slow:
      enabled: false
    prometheus-pushgateway:
      enabled: false
    kubernetes-services:
      enabled: false
    kubernetes-pods:
      enabled: false
    kubernetes-pods-slow:
      enabled: false

grafana:
  enabled: true

  adminUser: admin
  adminPassword: admin

  persistence:
    enabled: false

  service:
    type: ClusterIP

  resources:
    limits:
      memory: 256Mi
      cpu: 200m
    requests:
      memory: 128Mi
      cpu: 100m

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://pulse-hub-observability-prometheus-server
          isDefault: true
